packages:
  - docs
  - playground
  - packages/*
  - examples/*

allowBuilds:
  core-js: true
  core-js-pure: true
  esbuild: true
  vue-demi: true

catalog:
  # Root devDependencies
  "@biomejs/biome": "^2.5.12"
  "@dcloudio/types": "^3.4.32"
  # playground dependencies
  "@dcloudio/uni-app": "3.0.0-5000720260410001"
  "@dcloudio/uni-app-plus": "3.0.0-5000720260410001"
  # playground devDependencies
  "@dcloudio/uni-automator": "3.0.0-5000720260410001"
  "@dcloudio/uni-cli-shared": "3.0.0-5000720260410001"
  "@dcloudio/uni-components": "3.0.0-5000720260410001"
  "@dcloudio/uni-h5": "3.0.0-5000720260410001"
  "@dcloudio/uni-mp-alipay": "3.0.0-5000720260410001"
  "@dcloudio/uni-mp-baidu": "3.0.0-5000720260410001"
  "@dcloudio/uni-mp-kuaishou": "3.0.0-5000720260410001"
  "@dcloudio/uni-mp-lark": "3.0.0-5000720260410001"
  "@dcloudio/uni-mp-qq": "3.0.0-5000720260410001"
  "@dcloudio/uni-mp-toutiao": "3.0.0-5000720260410001"
  "@dcloudio/uni-mp-vue": "3.0.0-5000720260410001"
  "@dcloudio/uni-mp-weixin": "3.0.0-5000720260410001"
  "@dcloudio/uni-quickapp-webview": "3.0.0-5000720260410001"
  "@dcloudio/uni-stacktracey": "3.0.0-5000720260410001"
  "@dcloudio/vite-plugin-uni": "3.0.0-5000720260410001"
  "@lerna-lite/cli": "^5.6.1"
  "@lerna-lite/version": "^5.6.1"
  # packages/core dependencies
  "@types/lodash.merge": "^4.6.9"
  "@types/node": "^26.5.0"
  # packages/core devDependencies
  "@types/ungap__url-search-params": "^0.1.2"
  "@ungap/url-search-params": "^0.2.2"
  "@vitest/coverage-v8": "^4.1.11"
  "@vueuse/core": "^12.8.2"
  abort-controller: "^3.0.0"
  abortcontroller-polyfill: "^1.7.8"
  conventional-changelog-conventionalcommits: "^10.4.0"
  core-js: "^3.50.0"
  fast-querystring: "^1.1.2"
  is-ci: "^4.1.0"
  lodash.merge: "^4.6.2"
  rimraf: "^6.1.3"
  statuses-es: "^2.0.6"
  tsdown: "^0.23.0"
  typescript: "~6.0.3"
  vite: "^5.4.21"
  vite-plugin-uni-polyfill: "^0.1.0"
  # docs devDependencies
  vitepress: "^1.6.4"
  vitest: "^3.2.7"
  # Shared across packages
  vue: "~3.4.38"
  vue-demi: "^0.14.10"
  vue-i18n: "^9.14.5"

configDependencies:
  "@pnpm/plugin-trusted-deps": ^0.2.2
