name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  merge_group: {}

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [22, 24, 26]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          cache: true
          require-lockfile: true
          runtime: node@${{ matrix.node_version }}

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test

      - name: Check
        run: pnpm run check

      - name: Typecheck
        run: pnpm run typecheck

      - run: pnpm run play:build:mp-weixin

      - run: pnpm run play:build:h5
